export const projectHistory = [
	{
		year: 2024,
		name: 'Blog',
		description: 'My personal blog and digital area',
		url: 'https://github.com/gabrielccarvalho/blog',
		tech: ['React', 'Next', 'TypeScript'],
	},
	{
		year: 2024,
		name: 'Cardfy',
		description: 'A smart flashcards app with spaced repetition',
		url: 'https://github.com/gabrielccarvalho/cardfy',
		tech: ['React', 'Next', 'TypeScript'],
	},
	{
		year: 2024,
		name: 'Study App',
		description: 'A gamified way to study with friends.',
		url: 'https://github.com/gabrielccarvalho/study',
		tech: ['React', 'Next', 'TypeScript'],
	},
	{
		year: 2023,
		name: 'Finances',
		description: 'A finances app to track personal expenses.',
		url: 'https://github.com/gabrielccarvalho/finances',
		tech: ['React Native', 'TypeScript', 'Expo'],
	},
	{
		year: 2023,
		name: 'Free Resume',
		description: 'A resume generation platform',
		url: 'https://github.com/gabrielccarvalho/free-resume',
		tech: ['React', 'Next', 'TypeScript'],
	},
	{
		year: 2023,
		name: 'Upload AI',
		description: 'an AI powered video description and title generator',
		url: 'https://github.com/gabrielccarvalho/upload.ai',
		tech: ['React', 'Next', 'TypeScript'],
	},
	{
		year: 2023,
		name: 'Planner',
		description: 'A simple and beautiful planner.',
		url: 'https://github.com/gabrielccarvalho/Planner',
		tech: ['React Native', 'Expo', 'TypeScript'],
	},
	{
		year: 2022,
		name: 'One Finance',
		description: 'A finance app to track personal expenses.',
		url: 'https://github.com/gabrielccarvalho/OneFinance',
		tech: ['React Native', 'Expo', 'TypeScript'],
	},
	{
		year: 2022,
		name: 'Ignews',
		description: 'A newspaper platform.',
		url: 'https://github.com/gabrielccarvalho/ignews',
		tech: ['React', 'Next', 'TypeScript'],
	},
	{
		year: 2022,
		name: 'DevJobs API',
		description: 'Backend for @DevJobs.',
		url: 'https://github.com/gabrielccarvalho/DevJobs-api',
		tech: ['Node', 'TypeScript'],
	},
	{
		year: 2022,
		name: 'DevJobs',
		description: 'A platform to find developers and list jobs.',
		url: 'https://github.com/gabrielccarvalho/DevJobs-web',
		tech: ['React', 'Next', 'TypeScript'],
	},
	{
		year: 2022,
		name: 'Tindev',
		description: 'A tinder-like platform for meeting with developers',
		url: 'https://github.com/gabrielccarvalho/Tindev',
		tech: ['React Native', 'Expo', 'TypeScript'],
	},
	{
		year: 2022,
		name: 'Dashgo',
		description: 'A dashboard to study Chakra UI.',
		url: 'https://github.com/gabrielccarvalho/dashgo',
		tech: ['React', 'Next', 'TypeScript'],
	},
	{
		year: 2021,
		name: 'Weather App',
		description: 'A simple weather app.',
		url: 'https://github.com/gabrielccarvalho/weather-app',
		tech: ['React Native', 'Expo', 'TypeScript'],
	},
	{
		year: 2020,
		name: 'Easy Raffle',
		description: 'A raffle platform',
		url: 'https://github.com/gabrielccarvalho/easy-raffle-web',
		tech: ['React', 'Next', 'TypeScript'],
	},
	{
		year: 2020,
		name: 'Easy Raffle API',
		description: 'The backend for @EasyRaffle.',
		url: 'https://github.com/gabrielccarvalho/easy-raffle-api',
		tech: ['Node', 'TypeScript'],
	},
	{
		year: 2020,
		name: 'Calendar',
		description: 'A simple calendar app.',
		url: 'https://github.com/gabrielccarvalho/Calendar',
		tech: ['React Native', 'Expo', 'TypeScript'],
	},
	{
		year: 2019,
		name: 'Ignite Teams',
		description: 'A Microsoft-Teams inspired platform',
		url: 'https://github.com/gabrielccarvalho/ignite-teams',
		tech: ['React', 'TypeScript'],
	},
	{
		year: 2019,
		name: 'Rocketshoes',
		description: 'A e-commerce to study Redux.',
		url: 'https://github.com/gabrielccarvalho/rocketshoes',
		tech: ['React', 'TypeScript'],
	},
]
